### PR TITLE
Add facerec_from_webcam_multiprocessing.py

### PR DESCRIPTION
**Pull request by chn-lee-yumi**
- Modify from `facerec_from_webcam.py`
- Improve fps (each core processes one frame), but processing time is not improved.
- Has been tested on RPi 2B+, RPi 3B, Atom Z8300, i7-4710MQ.
- The more cores CPU have, the more improvement on video.
- Tested results:

| RPi 2B+|RPi 3B|Atom Z8300|i7-4710MQ|
|---------|------|-------------|------------|
|~0.65fps|~0.95fps|~2.5fps|~15fps|

- Bug: when hit 'q' to quit, some subprocess will throw out an exception, but all processes will exit.

### CODE REVIEW

**Comment by ageitgey** [comment]
Thanks!

**Comment by soundreactor** [comment]
we get `NameError: name 'Global' is not defined` in python 3.6
https://github.com/ageitgey/face_recognition/issues/809
what python version should be used?

**Comment by DevelopmentIsKey** [comment]
I have the same problem.
Could you please check the problem?

Thanks.

**Comment by Muplex** [comment]
NameError: name 'Global' is not defined
also for me
python version 3.7 and also 3.6

**Pull request merged**
