### PR TITLE
Necessary package Updated in requirements.txt

### PR DESCRIPTION
**Pull request by ayushmankumar7**
cmake=>3.14.4   added

### CODE REVIEW

**Comment by ageitgey** [comment]
Why?

**Comment by ayushmankumar7** [comment]
For using dlib , installing cmake is necessary, or else it throws a Runtime
Error stating " CMake must be installed to build the following extension:
dlib"

**Comment by ageitgey** [comment]
I think on most systems, people don't install cmake via pip. They install it via their system's built in package manager, like apt-get on debian/Ubuntu. So I'm thinking that making it a Python requirement would break a lot of people's systems.

**Comment by ayushmankumar7** [comment]
Hey,

I just signed the petition "News Broadcasting Standards Authority: DEMAND
STRICT ACTION against COMMUNAL NEWS DEBATES @RajatSharmaLive
@MIB_India @PrakashJavdekar @thepeeinghuman" and wanted to see if you could
help by adding your name.

Our goal is to reach 150,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/24KxHX2tp2

Thanks!
Ayushman

**Pull request closed without merging**
