### PR TITLE
Adding example for Jupyter Notebook, that demostrates how to track fa…

### PR DESCRIPTION
**Pull request by Rai220**
…ces on video in real time

This is very useful for those one, who can't run python directly on pc and using remote server, but want to test this library in real time.

### CODE REVIEW

**Comment by ageitgey** [comment]
Thank you for submitting this example. I think having notebook examples is a great idea.

Can you just make these two small tweaks before I merge it?

1. Can you add some introduction text to your notebook explaining what the example does and why it exists? For example, you might say that this is an example of detecting face locations in a Python notebook and note that you need OpenCV installed to try out this demo. Otherwise it's hard for a new user to understand what the example is doing.
2. Can you remove any commented-out lines of code in the example code?

Thanks!

**Comment by Rai220** [comment]
@ageitgey thank you for your notice. I have added comments, descriptions and instructions to code.

**Comment by ageitgey** [comment]
Thanks!

**Comment by tim20120526** [comment]
> @ageitgey thank you for your notice. I have added comments, descriptions and instructions to code.

emm...i could not find any face track im your commit....

**Pull request merged**
