### PR TITLE
Added an example with a SVM classifier to readme

### PR DESCRIPTION
**Pull request by AnandBaburajan**
Updated readme with an added example of using a SVM classifier to train multiple images per person and recognize them from an image.

### CODE REVIEW

**Comment by Nicoleta-Blidaru** [comment]
I found a mistake. 

 for person_img in pix:
        # Get the face encodings for the face in each image file
        face = face_recognition.load_image_file ( "dataset/" + person + "/" + person_img )
        face_enc = face_recognition.face_encodings ( face ) [0]

In the last line, is there face_recognition.face_encodings( face ) [0] ?

**Comment by AnandBaburajan** [comment]
Thanks. I'll fix it.

**Comment by Nicoleta-Blidaru** [comment]
@AnandBaburajan Great! But if I modify that line as iI said it gives me this error: IndexError: list index out of range

**Comment by AnandBaburajan** [comment]
That error usually comes up if no faces are detected in an image. If the error persists, it'd be helpful if you could provide some additional information on how to reproduce this issue.

**Comment by Nicoleta-Blidaru** [comment]
Well, I've only changed the trained database with the one used here https://www.pyimagesearch.com/2018/06/18/face-recognition-with-opencv-python-and-deep-learning/ (on which the k-nn classifier works well).

**Comment by AnandBaburajan** [comment]
The knn classifier in the examples skips a training image if no faces are detected and is therefore free of the IndexError.

**Pull request merged**
