### PR TITLE
Add support of external detected landmarks.

### PR DESCRIPTION
**Pull request by sashacmc**
Add landmark_points parameter to face_landmarks and face_encodings methods.
It will allow to use the library with external detected landmark points.

Landmarks detection provided by default get bad result for many cases with not directly frontal face,
but by mean of using external detected landmarks (e.g. from https://github.com/1adrianb/face-alignment) possible significant improve recognition.

### CODE REVIEW

**Comment by SaddamBInSyed** [comment]
@sashacmc 
Thanks for the PR.

Do you add any test py code for example directory to test the same?

Thanks

**Comment by sashacmc** [comment]
Dear @SaddamBInSyed,

I added recognize_faces_in_pictures_alt_landmarks.py example, which based on recognize_faces_in_pictures.py but use alternative landmarks detector.

**Comment by SaddamBInSyed** [comment]
Thanks @sashacmc .
Well appreciated.

**Comment by SaddamBInSyed** [comment]
@sashacmc 
Hi.
I have tested with my nano board but it seems fps is very low ( < 1 ).
I think the keypoints detection consumes more time.
but again thanks for your PR.

**Comment by sashacmc** [comment]
Dear @SaddamBInSyed,
Yes face_alignment landmark detection takes more time (especially in CPU mode, it also allow to use CUDA, but in this case example will be more complex).

But quality of detection significantly better. Now I working on project for private albums face detection/search. And default landmarks encoding, give bad result in 30% (and without any information that it bad, which give big amount of false matches). Landmarks from face_alignment failed only in 2-3% cases. And usually there are possibility (with additional algorithm) understand that encoding has bad quality.

**Comment by SaddamBInSyed** [comment]
@sashacmc 
Also,[ this is](https://github.com/610265158/Peppa_Pig_Face_Engine) one more cool face key point detection. I have tried personally and it seems same as face_alignment. 
if you can try and let me know your suggestions.

thank you once again.

**Comment by sashacmc** [comment]
So, it is additional reason to apply this pull request. :)

**Comment by ageitgey** [comment]
Thanks! Things are crazy right now (as it is for everyone) so I haven't really had a chance to look at the code but I will as soon as I have a free moment.

**Comment by vs0533** [comment]
> 亲爱的@SaddamBInSyed，
> 
> 我添加了identify_faces_in_pictures_alt_landmarks.py示例，该示例基于identify_faces_in_pictures.py，但使用了其他地标检测器。

hi  can you provide me with source code  ， thinks!

**Pull request closed without merging**
