### PR TITLE
Support for new dlib 19.7 stuff

### PR DESCRIPTION
**Pull request by ageitgey**
- Bump version to 1.1.0
- Require dlib 19.7 and face_recognition_models 0.3.0
- Support the new slimmer 5-point face post model when creating face encodings. This speed things up slightly (a few fps in some cases)
- Update docs/Dockerfile everywhere to say dlib 19.7 instead of dlib 19.5

See http://blog.dlib.net/2017/09/fast-multiclass-object-detection-in.html for context on dlib speed-ups

Now that redundant face pose models are being loaded, it makes sense to start lazy loading them to save ram (especially on an RPi). But I didn't do that yet because I haven't tested how it might interact with python's different multiprocessing modes when using more than one thread.

### CODE REVIEW

**Comment by lolstatsguy** [comment]
Great work as always. Two suggestions: The user is currently not able to set the type of model used in the face_encodings function. Also the use of "model" might be a bit ambigious because of "cnn" and "hog". Maybe use landmark_model instead?

**Comment by eloelo22** [comment]
@lolstatsguy this should answer your question https://github.com/ageitgey/face_recognition/issues/169

**Comment by lolstatsguy** [comment]
@eloelo22 I am very familar with dlib and these model-typed. I am refering to the changes is this commit. One model is used for detection the other one for landmarks. It might be better to change this in the code for better understanding. So "Hog" and "Cnn" may be renamend to "detection_model" and "small" and "large" to "landmark_model" because they are used very different in this libary which might be confusing

**Comment by eloelo22** [comment]
ow i am sorry i thought we had the same issue ✌️

**Comment by ageitgey** [comment]
@lolstatsguy the user can't set the model there because the new model is just a slimmer version of the existing model - it just returns less points for each face. It's mainly useful to speed up face recognition where not all points are needed. It's not really that useful on it's own (unless you are doing something pretty special and then might just use dlib directly anyway).

**Pull request merged**
